# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilmFest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'

  # Pods for FilmFest

  target 'FilmFestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
